### ISSUE TITLE
Old Issue Repeat

### ISSUE THREAD

**Issue by ajkothari13** [autolume/autolux#16]
Hello!
Writing after a long time. And here are my thoughts:

1.    AutoLux still does not differ between night and day. Mostly, I have to increase brightness manually during day and reduce after evening.
    I was hoping that it would have average / baseline measure for day and night separately. So, by looking at the system clock it would adjust whether to reduce or increase brightness.

 2.  Is there a way to mute the screenshot process of the tool? I think it makes some sound with every screenshot.

Thanks :)

**Comment by okayzed** [comment]
1) Can you share the plots produced by "--visualize --plot-luma" and "--visualize --plot-brightness" ? I'm curious to see what your model has learned. Right now, the model uses the X closest points in time and has to choose those X points from points in the same time bucket on different days and points in close by time buckets on the same day. 

2) The screenshot tool makes a sound? I didn't know it was possible - I'll look into it. fwiw, I have set it to only take a screenshot of a sub portion of the screen (specified via --crop parameter). the command being used to take screenshots is `import` from ImageMagick toolkit

**Comment by ajkothari13** [comment]
Hey Okayzed,

1. Here are [the plots](https://imgur.com/a/1foxs)
   Thanks for explaining how AutoLux works

2. The screenshot / crop sound is extremely frequent. No such sound if AutoLux is not on. The sound comes when i change from one page / screen / app  to another

I tried to find ImageMagick preference to shut down the sound, but didn't find any in the gui.

**Comment by okayzed** [comment]
1. I need to think on this more - thanks for the plots
2. I see there is a "-silent" option (https://github.com/ponty/pyscreenshot/issues/9) for `import` command - I can make the change tomorrow for it

**Comment by ajkothari13** [comment]
When I shifted to linux, had no idea how to adjust brightness from keyboard. 
I don't have any more headache and painful eyes.
Also, AutoLux is doing a fine job. It only takes time twice a day to manual adjustments.
Thanks a lot for being helpful :)

**Comment by okayzed** [comment]
I pushed a change to add "-silent" option for screenshots (version 0.33). Its funny it was doing that!

In your plots, I can see there is not as much spread in one of the axes as I would like (to create a differentiating signal). I'm still thinking about it. here's the equivalent image for me: https://imgur.com/a/LxFOc - you can see there is a clear time component that is being learnt (brightness changes by time of day). 

when i run autolux, i am cropping to only a small portion of the screen using: `autolux --crop "10x500+400+0"`  - it means to create a 10 px high by 500 px wide screenshot at 400 pixels from the top (and 0 from the left). - this is the upper / middle left corner. its possible that when you are taking full screenshots, many pages are looking similar because of white / bland backgrounds - if you use cropping, perhaps this can help. i am still thinking about other causes

**Comment by ajkothari13** [comment]
Not sure if my comments will be helpful in technical stuff and you don't have to answer this - why is it that full page screen-shots are not used? 

I have a big window on my right from which ample sun light comes through out till late evening like from 8am to 6pm. Not sure if this info helps.

I shall test the new version late in evening as have something really important to finish first.

**Comment by okayzed** [comment]
re: cropped screenshots: i used a cropped screenshot (to only 500x10 instead of 1920x1280) to reduce the amount of work that is done whenever a screenshot is taken. this is because i reduced the delay between screenshots to 400 - 500ms or so (because i want a faster response) but that caused the screenshotting to use more CPU. 

i was just guessing that perhaps a smaller screenshot area would give a different "luminence" profile to web pages.

**Comment by ajkothari13** [comment]
ok. you know better, i was just guessing from my limited knowledge :)

**Comment by okayzed** [comment]
closing from age
